### ISSUE TITLE
Version 4 / Android / No rating window displayed

### ISSUE THREAD

**Issue by vogloblinsky** [dpa99c/cordova-launch-review-example#2]
Hi,

Thanks for upgrading your plugin for native android rating support.

When i run this example project, the Android rating window is not displayed. Is there something wrong ?

**Comment by dpa99c** [comment]
You need to set the package name (`<widget id="">` in `config.xml`) to match that of a real app in the Play Store - `uk.co.workingedge.phonegap.plugins.example.launchreview` is not a real app. 

Then you will see something like this:
<img width="300" src="https://user-images.githubusercontent.com/2345062/92451721-0399b100-f1b5-11ea-9bad-79b8d2845c8b.png" />

**Comment by vogloblinsky** [comment]
Ok thanks, may be a reference in the doc should be fine ?
And for iOS, where did the plugin got the appId ?

**Comment by UzverNumber47** [comment]
I've set the real app id. "Launch Review" button works. But no luck with "Launch Inapp Rating".
"Alert Displayed rating dialog" is shown and nothing happens.
